apiVersion: v1
kind: Namespace
metadata:
  name: mywebsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mywebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: nginx-container
        image: techpedia/mywebsite:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"       # minimum CPU guaranteed
            memory: "256Mi"   # minimum memory guaranteed
          limits:
            cpu: "500m"       # maximum CPU allowed
            memory: "512Mi"   # maximum memory allowed
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mywebsite
spec:
  selector:
    app: mywebsite
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: mywebsite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # scale pods if CPU > 50%
