apiVersion: v1
kind: Namespace
metadata:
  name: mywebsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mywebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: techpedia/mywebsite:latest # replace with your repo/image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: web-namespace
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
  type: NodePort # change to LoadBalancer if on cloud (EKS, GKE, AKS)
