apiVersion: v1
kind: Namespace
metadata:
  name: mywebsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mywebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: nginx-container
        image: techpedia/mywebsite:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mywebsite
spec:
  selector:
    app: mywebsite   # ✅ same as Deployment label
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 80  # container port
  type: NodePort    # use LoadBalancer if on EKS/GKE/AKS
